// Mock data will go here
export const mockUsers = [
  {
    id: "u1",
    firstName: "Abebe",
    lastName: "Kebede",
    email: "abebe@gmail.com",
    password: "123456",
    phone: "0911234567",
    role: "LANDLORD",
  },
  {
    id: "u2",
    firstName: "Mulugeta",
    lastName: "Tadesse",
    email: "mulugeta@gmail.com",
    password: "123456",
    phone: "0922345678",
    role: "LANDLORD",
  },
  {
    id: "u3",
    firstName: "Tigist",
    lastName: "Alemu",
    email: "tigist@gmail.com",
    password: "123456",
    phone: "0933456789",
    role: "TENANT",
  },
  {
    id: "u4",
    firstName: "Hiwot",
    lastName: "Girma",
    email: "hiwot@gmail.com",
    password: "123456",
    phone: "0944567890",
    role: "TENANT",
  },
  {
    id: "u5",
    firstName: "Dawit",
    lastName: "Bekele",
    email: "dawit@gmail.com",
    password: "123456",
    phone: "0955678901",
    role: "SUBCITY_STAFF",
    subCityZone: "Bole",
  },
  {
    id: "u6",
    firstName: "Sara",
    lastName: "Haile",
    email: "sara@gmail.com",
    password: "123456",
    phone: "0966789012",
    role: "ADMINISTRATOR",
  },
];

export const mockProperties = [
  {
    id: "p1",
    ownerId: "u1",
    ownerName: "Abebe Kebede",
    propertyName: "Bole Apartments",
    address: "Bole Road, Near Stadium",
    subCity: "Bole",
    woreda: "Woreda 03",
    propertyType: "RESIDENTIAL",
    totalArea: 450,
    yearBuilt: 2015,
    latitude: 9.0054,
    longitude: 38.7636,
    isVerified: true,
  },
  {
    id: "p2",
    ownerId: "u1",
    ownerName: "Abebe Kebede",
    propertyName: "Kirkos Commercial Center",
    address: "Churchill Avenue",
    subCity: "Kirkos",
    woreda: "Woreda 07",
    propertyType: "COMMERCIAL",
    totalArea: 800,
    yearBuilt: 2010,
    latitude: 9.0105,
    longitude: 38.7612,
    isVerified: false,
  },
  {
    id: "p3",
    ownerId: "u2",
    ownerName: "Mulugeta Tadesse",
    propertyName: "Yeka Residence",
    address: "Yeka Sub-city, Near Church",
    subCity: "Yeka",
    woreda: "Woreda 11",
    propertyType: "RESIDENTIAL",
    totalArea: 320,
    yearBuilt: 2018,
    latitude: 9.0301,
    longitude: 38.7891,
    isVerified: true,
  },
  {
    id: "p4",
    ownerId: "u2",
    ownerName: "Mulugeta Tadesse",
    propertyName: "Arada Mixed Use Building",
    address: "Piazza Area, Arada",
    subCity: "Arada",
    woreda: "Woreda 02",
    propertyType: "MIXED_USE",
    totalArea: 600,
    yearBuilt: 2008,
    latitude: 9.0227,
    longitude: 38.7468,
    isVerified: true,
  },
];

export const mockUnits = [
  {
    id: "un1",
    propertyId: "p1",
    unitNumber: "A-101",
    floorArea: 85,
    floorLevel: 1,
    numberOfRooms: 2,
    hasParking: true,
    hasElevator: false,
    amenities: "Water, Electricity, Internet",
  },
  {
    id: "un2",
    propertyId: "p1",
    unitNumber: "A-102",
    floorArea: 65,
    floorLevel: 1,
    numberOfRooms: 1,
    hasParking: false,
    hasElevator: false,
    amenities: "Water, Electricity",
  },
  {
    id: "un3",
    propertyId: "p2",
    unitNumber: "B-001",
    floorArea: 120,
    floorLevel: 0,
    numberOfRooms: 3,
    hasParking: true,
    hasElevator: true,
    amenities: "Water, Electricity, Generator, Internet",
  },
  {
    id: "un4",
    propertyId: "p3",
    unitNumber: "C-201",
    floorArea: 90,
    floorLevel: 2,
    numberOfRooms: 2,
    hasParking: false,
    hasElevator: true,
    amenities: "Water, Electricity",
  },
  {
    id: "un5",
    propertyId: "p4",
    unitNumber: "D-101",
    floorArea: 150,
    floorLevel: 1,
    numberOfRooms: 4,
    hasParking: true,
    hasElevator: true,
    amenities: "Water, Electricity, Generator, Guard, Internet",
  },
];

export const mockContracts = [
  {
    id: "c1",
    unitId: "un1",
    tenantId: "u3",
    landlordId: "u1",
    tenantName: "Tigist Alemu",
    landlordName: "Abebe Kebede",
    propertyAddress: "Bole Road, Near Stadium - Unit A-101",
    startDate: "2024-01-01",
    endDate: "2024-12-31",
    monthlyRent: 12000,
    currency: "ETB",
    status: "ACTIVE",
    termsAndConditions: "Standard rental terms apply.",
    tenantSignature: "Tigist Alemu",
    rejectionReason: null,
  },
  {
    id: "c2",
    unitId: "un2",
    tenantId: "u4",
    landlordId: "u1",
    tenantName: "Hiwot Girma",
    landlordName: "Abebe Kebede",
    propertyAddress: "Bole Road, Near Stadium - Unit A-102",
    startDate: "2024-03-01",
    endDate: "2025-02-28",
    monthlyRent: 8500,
    currency: "ETB",
    status: "PENDING_CONFIRMATION",
    termsAndConditions: "Standard rental terms apply.",
    tenantSignature: null,
    rejectionReason: null,
  },
  {
    id: "c3",
    unitId: "un3",
    tenantId: "u3",
    landlordId: "u1",
    tenantName: "Tigist Alemu",
    landlordName: "Abebe Kebede",
    propertyAddress: "Churchill Avenue - Unit B-001",
    startDate: "2023-06-01",
    endDate: "2024-05-31",
    monthlyRent: 35000,
    currency: "ETB",
    status: "UNDER_APPEAL",
    termsAndConditions: "Commercial rental terms apply.",
    tenantSignature: "Tigist Alemu",
    rejectionReason: null,
  },
  {
    id: "c4",
    unitId: "un4",
    tenantId: "u4",
    landlordId: "u2",
    tenantName: "Hiwot Girma",
    landlordName: "Mulugeta Tadesse",
    propertyAddress: "Yeka Sub-city - Unit C-201",
    startDate: "2024-02-01",
    endDate: "2025-01-31",
    monthlyRent: 9500,
    currency: "ETB",
    status: "DRAFT",
    termsAndConditions: "Standard rental terms apply.",
    tenantSignature: null,
    rejectionReason: null,
  },
];

export const mockDeclarations = [
  {
    id: "d1",
    contractId: "c1",
    declarationPeriod: "2024-01-01",
    declaredRent: 12000,
    aiBenchmarkRent: 13500,
    anomalyScore: 0.11,
    isAnomaly: false,
    anomalyReason: null,
    estimatedTax: 1200,
    isVerified: true,
  },
  {
    id: "d2",
    contractId: "c1",
    declarationPeriod: "2024-02-01",
    declaredRent: 12000,
    aiBenchmarkRent: 13500,
    anomalyScore: 0.11,
    isAnomaly: false,
    anomalyReason: null,
    estimatedTax: 1200,
    isVerified: false,
  },
  {
    id: "d3",
    contractId: "c3",
    declarationPeriod: "2024-01-01",
    declaredRent: 8000,
    aiBenchmarkRent: 32500,
    anomalyScore: 0.94,
    isAnomaly: true,
    anomalyReason: "Possible under-declaration",
    estimatedTax: 800,
    isVerified: false,
  },
];

export const mockAppeals = [
  {
    id: "ap1",
    contractId: "c3",
    tenantId: "u3",
    tenantName: "Tigist Alemu",
    appealType: "RENT_INCREASE",
    reason:
      "The landlord has increased the rent by 40% without prior notice or valid justification. This exceeds the legal limit.",
    status: "PENDING",
    resolutionNotes: null,
    resolutionDecision: null,
    createdAt: "2024-03-15",
  },
  {
    id: "ap2",
    contractId: "c1",
    tenantId: "u3",
    tenantName: "Tigist Alemu",
    appealType: "CONTRACT_TERMINATION",
    reason: "Landlord is attempting to terminate contract before end date without legal grounds.",
    status: "RESOLVED",
    resolutionNotes: "Appeal reviewed. Contract termination deemed unlawful.",
    resolutionDecision: "Approved - Contract remains active",
    createdAt: "2024-02-10",
  },
];

export const mockBenchmark = {
  suggestedRent: 13500,
  minRent: 11475,
  maxRent: 15525,
  confidenceScore: 0.85,
  marketTrend: "STABLE",
  reasoning:
    "Based on 47 similar residential properties in Bole sub-city. 2-bedroom units averaging 85m² are currently renting between ETB 11,475 and ETB 15,525 per month.",
};